//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursV2.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_data
    {
        public int Id { get; set; }
        public int Id_product { get; set; }
        public Nullable<int> Price { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> Sum { get; set; }
        public int Order_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
